server:
  port: 8080

spring:
  application:
    name: api-gateway # Define the application name for Eureka registration
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**

        - id: restaurant-service
          uri: lb://restaurant-service
          predicates:
            - Path=/api/restaurant/**

# Eureka Client Configuration - THIS IS WHAT WAS MISSING
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka # IMPORTANT: Make sure this URL matches your Eureka server's address
    register-with-eureka: true # Tells the API Gateway to register itself with Eureka
    fetch-registry: true     # Allows the API Gateway to fetch the service registry from Eureka

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
