
server:
  port: 8081

spring:
  application:
    name: auth-service
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/authdb
    username: root
    password: Hhdh573)&@/dg
  jpa:
    hibernate:
      ddl-auto: create-drop
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 296213856457-gg173ol8lv47v4k44o278nggfvgbpbha.apps.googleusercontent.com
            client-secret: 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
            scope: profile,email
          github:
            client-id: Ov23li17sCjXfTr16ZjK
            client-secret: 34143867cf2a4c6a3a0afae0ce1ab9c4110d1293
        provider:
          google:
            user-name-attribute: email
          github:
            user-name-attribute: login

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka # Assuming Eureka is running here
    register-with-eureka: true
    fetch-registry: true


jwt:
    secret: QTYFlMvKRvuKRJXFKR97Gxd9KRvuKRJXFKR97Gxd9KRvuKRJXFKR97Gxd9KRvuKRJXFKR97Gxd9 # Your provided secret
    expiration: 3600000
    refresh-expiration: 604800000





