server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authdb
    username: root
    password: Hhdh573)&@/dg
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: auth-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

